[package]
name = "pos-plugin-bridges"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish.workspace = true

[dependencies]
pos-core = { path = "../../crates/pos-core" }
pos-plugin-geo = { path = "../geo" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ciborium = { workspace = true }

[lints]
workspace = true
