[package]
name = "pos-core"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_bytes = "0.11"
ciborium = { workspace = true }
ulid = { workspace = true }
bytes = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
