[package]
name = "pos-time"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
pos-core  = { path = "../pos-core" }
pos-store = { path = "../pos-store" }
pos-state = { path = "../pos-state" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
pos-store = { path = "../pos-store", features = ["sqlite"] }

[lints]
workspace = true
