[package]
name = "pos-query"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
pos-core = { path = "../pos-core" }

[dev-dependencies]
pos-core = { path = "../pos-core", features = ["test-support"] }
pos-store = { path = "../pos-store" }

[lints]
workspace = true
