[package]
name = "pos-query"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
pos-core  = { path = "../pos-core" }
pos-store = { path = "../pos-store" }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
