[package]
name = "pos-sandboxd"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
pos-reference = { path = "../../crates/pos-reference" }
thiserror = { workspace = true }
zbus = { version = "=5.19.0", default-features = false, features = [
  "p2p",
  "tokio",
] }
zbus_systemd = { version = "=0.26100.0", default-features = false, features = [
  "systemd1",
  "zbus-async-tokio",
] }
zvariant = "=5.15.0"

[dev-dependencies]
pos-conformance = { path = "../../crates/pos-conformance" }
tokio = { workspace = true }

[lints]
workspace = true
