[package]
name = "piglor-world-client"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "piglor_world_client"
path = "src/lib.rs"

[dependencies]
blake3 = { workspace = true }
ciborium = { workspace = true }
pos-core = { path = "../../crates/pos-core" }
pos-state = { path = "../../crates/pos-state" }
pos-plugin-society = { path = "../../plugins/society" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ulid = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[lints]
workspace = true
