[package]
name = "piglor-world-client"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["runtime"]
runtime = ["dep:bevy", "dep:wasm-bindgen"]

[lib]
name = "piglor_world_client"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { version = "=0.19.0", default-features = false, features = [
  "3d_bevy_render",
  "bevy_winit",
  "custom_cursor",
  "default_app",
  "default_font",
  "multi_threaded",
  "picking",
  "scene",
  "std",
  "sysinfo_plugin",
  "webgl2",
  "x11",
], optional = true }
blake3 = { workspace = true }
ciborium = { workspace = true }
pos-core = { path = "../../crates/pos-core" }
pos-state = { path = "../../crates/pos-state" }
pos-plugin-society = { path = "../../plugins/society" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ulid = { workspace = true }
wasm-bindgen = { version = "0.2", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.4.3", default-features = false, features = [
  "wasm_js",
] }
getrandom03 = { package = "getrandom", version = "0.3.4", default-features = false, features = [
  "wasm_js",
] }

[lints]
workspace = true
