[package]
name = "pos-plugin-geo"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish.workspace = true

[features]
default = []
h3 = ["dep:h3o"]

[dependencies]
pos-core = { path = "../../crates/pos-core" }
pos-crypto = { path = "../../crates/pos-crypto" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ciborium = { workspace = true }
h3o = { version = "=0.11.0", default-features = false, optional = true }

[lints]
workspace = true
