#![allow(clippy::module_name_repetitions)]

use serde::{Deserialize, Serialize};
use std::cell::RefCell;
use std::fmt;
use ulid::{Generator, Ulid};

thread_local! {
    static ULID_GEN: RefCell<Generator> = const { RefCell::new(Generator::new()) };
}

/// Generate a monotonically increasing ULID using the thread-local generator.
fn gen_ulid() -> Ulid {
    ULID_GEN.with(|g| {
        // Overflow / clock-regression is not realistically inducible in unit tests.
        g.borrow_mut()
            .generate()
            .expect("ULID monotonic generator overflow or clock regression")
    })
}

macro_rules! ulid_newtype {
    ($name:ident, $doc:literal) => {
        #[doc = $doc]
        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
        #[serde(transparent)]
        pub struct $name(Ulid);

        impl $name {
            pub fn new() -> Self {
                Self(gen_ulid())
            }

            pub const fn from_ulid(ulid: Ulid) -> Self {
                Self(ulid)
            }

            pub const fn inner(&self) -> Ulid {
                self.0
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::new()
            }
        }

        impl fmt::Debug for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}({})", stringify!($name), self.0)
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}", self.0)
            }
        }
    };
}

ulid_newtype!(EntityId, "Unique identifier for an entity.");
ulid_newtype!(EventId, "Unique identifier for an event.");
ulid_newtype!(TimelineId, "Unique identifier for a timeline.");
ulid_newtype!(CorrelationId, "Groups related events into a logical transaction.");
ulid_newtype!(PluginId, "Identifies a registered plugin.");
ulid_newtype!(RelationshipId, "Unique identifier for a relationship.");

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_ids_are_unique() {
        let a = EntityId::new();
        let b = EntityId::new();
        assert_ne!(a, b);
    }

    #[test]
    fn ids_are_monotonically_ordered_within_process() {
        let ids: Vec<EntityId> = (0..100).map(|_| EntityId::new()).collect();
        for window in ids.windows(2) {
            assert!(window[0] <= window[1]);
        }
    }

    #[test]
    fn id_serde_json_round_trip() {
        let id = EventId::new();
        let s = serde_json::to_string(&id).unwrap();
        let back: EventId = serde_json::from_str(&s).unwrap();
        assert_eq!(id, back);
    }

    #[test]
    fn id_serde_cbor_round_trip() {
        let id = TimelineId::new();
        let mut buf = Vec::new();
        ciborium::into_writer(&id, &mut buf).unwrap();
        let back: TimelineId = ciborium::from_reader(buf.as_slice()).unwrap();
        assert_eq!(id, back);
    }

    #[test]
    fn all_id_types_are_copy() {
        fn assert_copy<T: Copy>() {}
        assert_copy::<EntityId>();
        assert_copy::<EventId>();
        assert_copy::<TimelineId>();
        assert_copy::<CorrelationId>();
        assert_copy::<PluginId>();
        assert_copy::<RelationshipId>();
    }

    #[test]
    fn id_from_ulid_round_trip() {
        let ulid = Ulid::gen();
        let id = EntityId::from_ulid(ulid);
        assert_eq!(id.inner(), ulid);
    }

    #[test]
    fn id_display_is_ulid_string() {
        let ulid = Ulid::gen();
        let id = EntityId::from_ulid(ulid);
        assert_eq!(id.to_string(), ulid.to_string());
    }

    #[test]
    fn different_id_types_have_different_debug() {
        let entity = EntityId::new();
        let event = EventId::new();
        assert!(format!("{entity:?}").starts_with("EntityId("));
        assert!(format!("{event:?}").starts_with("EventId("));
    }

    #[test]
    fn relationship_id_is_unique() {
        let a = RelationshipId::new();
        let b = RelationshipId::new();
        assert_ne!(a, b);
    }

    #[test]
    fn default_impl_produces_valid_id() {
        // Exercises the Default::default() path generated by ulid_newtype! for each id type.
        let _entity = EntityId::default();
        let _event = EventId::default();
        let _timeline = TimelineId::default();
        let _correlation = CorrelationId::default();
        let _plugin = PluginId::default();
        let _relationship = RelationshipId::default();
        // Two defaults should produce different ids (calls Self::new() each time).
        let a = EntityId::default();
        let b = EntityId::default();
        assert_ne!(a, b);
    }

    proptest::proptest! {
        #[test]
        fn ord_is_total_for_entity_ids(a: u128, b: u128) {
            let ia = EntityId::from_ulid(Ulid::from(a));
            let ib = EntityId::from_ulid(Ulid::from(b));
            let lt = ia < ib;
            let eq = ia == ib;
            let gt = ia > ib;
            assert_eq!(u8::from(lt) + u8::from(eq) + u8::from(gt), 1);
        }

        #[test]
        fn ord_stable_after_serde(a: u128, b: u128) {
            let ia = EntityId::from_ulid(Ulid::from(a));
            let ib = EntityId::from_ulid(Ulid::from(b));
            let ia2: EntityId = serde_json::from_str(&serde_json::to_string(&ia).unwrap()).unwrap();
            let ib2: EntityId = serde_json::from_str(&serde_json::to_string(&ib).unwrap()).unwrap();
            assert_eq!(ia.cmp(&ib), ia2.cmp(&ib2));
        }
    }
}
